version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - '/srv/dev-disk-by-id-usb-SABRENT_SABRENT_DB9876543214E-0-0-part1/Plex:/config'
      - '/srv/dev-disk-by-id-usb-SABRENT_SABRENT_DB9876543214E-0-0-part1/Series:/Series'
      - '/srv/dev-disk-by-id-usb-SABRENT_SABRENT_DB9876543214E-0-0-part1/Movies:/Movies'
      - '/srv/dev-disk-by-id-usb-SABRENT_SABRENT_DB9876543214E-0-0-part1/Music:/Music'
    restart: unless-stopped
