version: '2'
services:
    transmission-openvpn:
        volumes:
            - '/srv/dev-disk-by-id-ata-Samsung_SSD_840_EVO_250GB_mSATA_S1KPNSAF500258Y-part4/Transmission/Downloads:/Downloads'
            - '/srv/dev-disk-by-id-ata-Samsung_SSD_840_EVO_250GB_mSATA_S1KPNSAF500258Y-part4/Transmission/Series:/Series'
            - '/srv/dev-disk-by-id-ata-Samsung_SSD_840_EVO_250GB_mSATA_S1KPNSAF500258Y-part4/Transmission/Movies:/Movies'
            - '/srv/dev-disk-by-id-ata-Samsung_SSD_840_EVO_250GB_mSATA_S1KPNSAF500258Y-part4/Transmission/Music:/Music'
            - '/etc/localtime:/etc/localtime:ro'
            - '/srv/dev-disk-by-id-ata-Samsung_SSD_840_EVO_250GB_mSATA_S1KPNSAF500258Y-part4/Config/OpenVPN/FR_France_15765.ovpn:/etc/openvpn/custom/default.ovpn'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_USERNAME=client_10550
            - OPENVPN_PASSWORD=uCz6Ux1p3d
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - TRANSMISSION_WEB_UI=transmission-web-control
            - TRANSMISSION_DOWNLOAD_DIR=/Downloads
        cap_add:
            - NET_ADMIN
        dns:
            - 8.8.8.8
            - 8.8.4.4
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        restart: unless-stopped